package com.tuxdave;

import JComponents.JPlaceHolderTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class AnimeDownloader extends JFrame {
    private JPanel panel1;
    private JLabel info2;
    private JTextField info3;
    private JLabel info1;
    private JTextArea showLinkArea;
    private JButton copiaButton;
    private JButton salvaSuFileButton;
    private JPlaceHolderTextField LinkEdit;
    private JButton downloadComingSoonButton;
    private JProgressBar progressBar1;
    private JButton findEpisodesButton;

    //START AUTOGENERATED CODE

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-1));
        Font panel1Font = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, panel1.getFont());
        if (panel1Font != null) panel1.setFont(panel1Font);
        LinkEdit = new JPlaceHolderTextField();
        Font LinkEditFont = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, LinkEdit.getFont());
        if (LinkEditFont != null) LinkEdit.setFont(LinkEditFont);
        LinkEdit.setPlaceHolder("https://www.animeworld.tv/...");
        panel1.add(LinkEdit, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        info2 = new JLabel();
        Font info2Font = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, info2.getFont());
        if (info2Font != null) info2.setFont(info2Font);
        info2.setText("Inserisci il link della serie Anime:");
        panel1.add(info2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        info1 = new JLabel();
        info1.setBackground(new Color(-1));
        Font info1Font = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, info1.getFont());
        if (info1Font != null) info1.setFont(info1Font);
        info1.setForeground(new Color(-16777216));
        info1.setText("Recupera il link della serie Anime da Qui:");
        panel1.add(info1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        info3 = new JTextField();
        info3.setBackground(new Color(-1));
        info3.setEditable(false);
        Font info3Font = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, info3.getFont());
        if (info3Font != null) info3.setFont(info3Font);
        info3.setForeground(new Color(-9613313));
        info3.setText("https://www.animeworld.tv/");
        panel1.add(info3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        showLinkArea = new JTextArea();
        showLinkArea.setEditable(false);
        Font showLinkAreaFont = this.$$$getFont$$$("Ubuntu", Font.PLAIN, 14, showLinkArea.getFont());
        if (showLinkAreaFont != null) showLinkArea.setFont(showLinkAreaFont);
        showLinkArea.setText("");
        panel1.add(showLinkArea, new GridConstraints(3, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(400, 500), new Dimension(150, 50), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        salvaSuFileButton = new JButton();
        Font salvaSuFileButtonFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, salvaSuFileButton.getFont());
        if (salvaSuFileButtonFont != null) salvaSuFileButton.setFont(salvaSuFileButtonFont);
        salvaSuFileButton.setText("Salva su file!");
        panel2.add(salvaSuFileButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        copiaButton = new JButton();
        Font copiaButtonFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, copiaButton.getFont());
        if (copiaButtonFont != null) copiaButton.setFont(copiaButtonFont);
        copiaButton.setText("Copia!");
        panel2.add(copiaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        downloadComingSoonButton = new JButton();
        Font downloadComingSoonButtonFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 14, downloadComingSoonButton.getFont());
        if (downloadComingSoonButtonFont != null) downloadComingSoonButton.setFont(downloadComingSoonButtonFont);
        downloadComingSoonButton.setText("Download (Coming Soon)");
        panel2.add(downloadComingSoonButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        progressBar1 = new JProgressBar();
        panel1.add(progressBar1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        findEpisodesButton = new JButton();
        findEpisodesButton.setText("Trova Episodi!");
        panel1.add(findEpisodesButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    //END AUTOGENERATED CODE

    {
        add(panel1);
    }
}
